trigger:
- aws-LiftAndShift
pool: myselfhosted
steps:
- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    goals: 'install'
    publishJUnitResults: false
    javaHomeOption: 'JDKVersion'
    mavenVersionOption: 'Default'
    mavenAuthenticateFeed: false
    effectivePomSkip: false
    sonarQubeRunAnalysis: false